name: automated-testing
on: [push]
jobs:
  run-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Run unit tests
        run: cd api
        run: pytest unit_test.py
        run: cd ..

      - name: Build docker container
        run: docker-compose build
      
      - name: Run docker container
        run: docker-compose up -d

      - name: Run integration tests
        run: cd api
        run: pytest integration_test.py
